blueprint:
  name: Four Button Switch - Two Light Groups
  description: |
    Control two light groups with a four-button switch.
    - Button 1: Turn on first light
    - Button 2: Turn on second light
    - Button 3: Turn off first light
    - Button 4: Turn off second light
  domain: automation
  input:
    switch_device:
      name: Switch Device
      description: The four-button switch to use
      selector:
        device:
          filter:
            - integration: mqtt
    first_light:
      name: First Light/Group
      description: The first light or light group to control (buttons 1 and 3)
      selector:
        target:
          entity:
            - domain: light
    second_light:
      name: Second Light/Group
      description: The second light or light group to control (buttons 2 and 4)
      selector:
        target:
          entity:
            - domain: light
    circadian_switch:
      name: Circadian Lighting Switch (Optional)
      description: Optional circadian lighting switch to control brightness and color temperature
      default: []
      selector:
        entity:
          filter:
            - domain: switch
              integration: circadian_lighting

triggers:
  - domain: mqtt
    device_id: !input switch_device
    type: action
    subtype: press_1
    trigger: device
    id: top-on
  - domain: mqtt
    device_id: !input switch_device
    type: action
    subtype: press_3
    trigger: device
    id: top-off
  - domain: mqtt
    device_id: !input switch_device
    type: action
    subtype: press_2
    trigger: device
    id: bottom-on
  - domain: mqtt
    device_id: !input switch_device
    type: action
    subtype: press_4
    trigger: device
    id: bottom-off

conditions: []

actions:
  - variables:
      _circadian: !input circadian_switch

  - choose:
      - conditions:
          - condition: trigger
            id:
              - top-on
        sequence:
          - service: light.turn_on
            target: !input first_light
            data: >
              {% if _circadian %}
                {
                  "kelvin": {{ state_attr(_circadian, 'colortemp') | int }},
                  "brightness_pct": {{ state_attr(_circadian, 'brightness') | int }}
                }
              {% else %}
                {}
              {% endif %}
      - conditions:
          - condition: trigger
            id:
              - top-off
        sequence:
          - service: light.turn_off
            target: !input first_light
      - conditions:
          - condition: trigger
            id:
              - bottom-on
        sequence:
          - service: light.turn_on
            target: !input second_light
            data: >
              {% if _circadian %}
                {
                  "kelvin": {{ state_attr(_circadian, 'colortemp') | int }},
                  "brightness_pct": {{ state_attr(_circadian, 'brightness') | int }}
                }
              {% else %}
                {}
              {% endif %}
      - conditions:
          - condition: trigger
            id:
              - bottom-off
        sequence:
          - service: light.turn_off
            target: !input second_light

mode: single
